<header id="inicio">
  <h1>PI - Pisos &amp; Inmuebles</h1>
  <h2>PORTAL DE ANUNCIOS DE VENTA Y ALQUILER DE VIVIENDAS</h2>
</header>

<nav>
  <ul>
    <li><a href="/phpDAW/"><i class="icon-home"></i><strong>INICIO</strong></a></li>
    <li><a href="registro"><i class="icon-registro"></i><strong>REGISTRO</strong></a></li>
    <li><a href="index_logueado"><i class="icon-login"></i><strong>INICIAR SESIÓN</strong></a></li>
    <li><a href="busqueda"><i class="icon-search"></i><strong>BÚSQUEDA</strong></a></li>
  </ul>
</nav>
