<footer>
  <p><i class="icon-copyright"></i>2025 PI - Pisos &amp; Inmuebles.</p>
  <p>
    Autores: Silvia Balmaseda y Carmen Valle
    <a href="accesibilidad.php" title="Declaración de accesibilidad" style="color: inherit; text-decoration: underline;">
      <i class="icon-info" style="font-size: 1rem;"></i>
    </a>   
  </p>
</footer>

<script src="js/index.js"></script>
</body>
</html>
